FORMAT: 1A
HOST: http://ciis.apiblueprint.org/

# CzechInvest information system  - ciis

Public API for brownfields, real-estates and other publicly available databses, manged by CzechInvest

## Brownfields [/brownfields]

### List of all brownfields [GET]

+ Response 200 (text/html)

        <html>
        <head><title>Brownfields</title></head>
        <body>
        </body>
        </html>

## Brownfields JSON [/brownfields/json]

### List of all brownfields in JSON format[GET]

+ Response 200 (application/json)

        {
            "start": 0,
            "end": 1000,
            [
                {
                    "id": "uuid",
                    "name": "brownfield name",
                }
            ]
        }