FORMAT: 1A
HOST: http://ciis.apiblueprint.org/

# CzechInvest information system  - ciis

Public API for brownfields, real-estates and other publicly available databses, manged by CzechInvest

## Brownfields JSON [/api/brownfields/]

### List of all brownfields in JSON format[GET]

+ Response 200 (application/json)

        {
            "start": 0,
            "end": 1000,
            [
                {
                    "id": "uuid",
                    "name": "brownfield name",
                }
            ]
        }
